### ISSUE TITLE
Append shell command in neovim?

### ISSUE THREAD

**Issue by mhartington** [cormacrelf/dark-notify#1]
Currently there's an option to run a shell command when calling dark-notify directly. Is that possible when inside neovim?

**Comment by cormacrelf** [comment]
If I take it literally, yes of course you can run any shell command including `dark-notify -c blah` from inside neovim. Not sure how that helps you do anything though, and it would take over the UI if you just did `:!dark-notify -c blah`. Isn't it the case that you can have multiple neovim instances running, and anything external you'd want to do would be better served by writing a launchd daemon?

I think maybe you mean "run custom lua function when it changes". That would hit things like "extend dark-notify to support X status bar thing". I think it'd be about a 2-line change to support a `{ onchange = function(mode) ... end }` config option. Is that what you want?

**Comment by cormacrelf** [comment]
To further add why it's a confusing question, the way it works now is that the Lua plugin maintains a child process, and needs to read the output of the child process. If you added `-c myprogram`, it wouldn't necessarily produce output in the exact way the Lua plugin expects. So no, you can't simply add a user-configurable `-c myprogram` without ruining it, but I'm also puzzled as to why you would want that.
