### ISSUE TITLE
Opposite colour flash during nvim startup

### ISSUE THREAD

**Issue by willmcpherson2** [cormacrelf/dark-notify#3]
When macOS is in dark mode and I invoke `nvim`, the screen flashes white.

However, if I have `dn.update()` in my `init.vim`, the opposite happens, i.e. in light mode the screen flashes black.

This only happens with `colorscheme toast`, presumably because it allows `set background=light`/`set background=dark`

# Reproduce

1. Install the [toast](https://github.com/jsit/toast.vim) colorscheme
2. Switch to dark mode in macOS
3. Run `nvim`

**Comment by cormacrelf** [comment]
I think this is because the initial output of the dark-notify is immediate but is treated like a regular async event for simplicity. This would require either a separate dark-notify invocation for the initial setup, or some method of blocking on the libuv event loop. I think you can block it but would have to look into it a bit further.

**Comment by willmcpherson2** [comment]
This seems to be fixed now.

Just tested using this `init.lua`:

```lua
require "paq" {           
  "cormacrelf/dark-notify"; 
}

local dn = require("dark_notify")
dn.run()
dn.update()
```

No issues when opening neovim or when switching light/dark while neovim is open.

**Comment by nathanielks** [comment]
Noting for future readers: Make sure you don't have a colorscheme defined in your config while using this (at least if you're using [LunarVim](https://www.lunarvim.org/)). My editor would flash whatever colorscheme I had defined, then `dark-notify` would kick in with whatever colorscheme I had defined for the current system light/dark setting. Leave the setting of colorscheme to dark notify 👍
